In [ ]:
!pip install tensorflow_text

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 52.8 MB/s eta 0:00:00


In [ ]:
import tensorflow_hub as hub
import tensorflow_text as text


In [ ]:
preprocessing_url = 'https://kaggle.com/models/tensorflow/bert/TensorFlow2/en-uncased-preprocess/3'
encoder_url = 'https://www.kaggle.com/models/tensorflow/bert/TensorFlow2/bert-en-uncased-l-12-h-768-a-12/2'

In [ ]:
bert_processmodel = hub.KerasLayer(preprocessing_url)

In [ ]:
text_input = ['this is a nice car','this is a nice house','birds are very beautiful']
text_preprocessed = bert_processmodel(text_input)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_word_ids', 'input_mask'])

In [ ]:
text_preprocessed['input_mask']
# tokenisation in bert
# cls this is a nice car SEP therefore 7 total

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0

In [ ]:
text_preprocessed['input_type_ids']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0

In [ ]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[ 101, 2023, 2003, 1037, 3835, 2482,  102,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [ 101, 2023, 2003, 1037, 3835, 2160,  102,    0,    0,    0,    0,
           0,

In [ ]:
bert_modl_encoder = hub.KerasLayer(encoder_url)
bert_results = bert_modl_encoder(text_preprocessed)
bert_results.keys() # these things are saved in a dictionary..

dict_keys(['encoder_outputs', 'pooled_output', 'default', 'sequence_output'])

In [ ]:
bert_results['pooled_output'] # these are embeddings for the complete sentence

<tf.Tensor: shape=(3, 768), dtype=float32, numpy=
array([[ 0.3370886 , -0.28811154,  0.98445886, ..., -0.97902036,
         0.1506627 ,  0.99964905],
       [ 0.45694533,  0.00521136,  0.99672216, ..., -0.99633753,
         0.2390261 ,  0.9997076 ],
       [ 0.16464514, -0.28779393,  0.9648228 , ..., -0.99034625,
         0.3485497 ,  0.98003304]], dtype=float32)>

In [ ]:
bert_results['sequence_output'] # these are embeddings for each word in the sentence

<tf.Tensor: shape=(3, 128, 768), dtype=float32, numpy=
array([[[-1.3922510e-01,  7.4971065e-02,  2.7917752e-01, ...,
          1.1806604e-01,  9.8566435e-02, -1.2189561e+00],
        [ 6.3849431e-01,  2.3071161e-01,  5.0630617e-01, ...,
          5.2123707e-02, -7.2070509e-02, -6.9689786e-01],
        [ 2.6383325e-01, -4.8313327e-03,  6.4804274e-01, ...,
          5.7540798e-01,  6.6669017e-01, -1.5009600e+00],
        ...,
        [-9.5335394e-02,  5.2971375e-01,  8.5916765e-02, ...,
          9.1457859e-02,  2.1968581e-02, -6.6107321e-01],
        [-1.4263242e-03,  5.4562956e-01,  5.9161052e-02, ...,
         -8.3110094e-02,  8.3597124e-02, -3.3332646e-01],
        [ 1.4064354e-01,  8.6367294e-02,  3.0237529e-01, ...,
          2.2777970e-01,  1.7793791e-01, -7.8872401e-01]],

       [[ 7.1417764e-03,  1.0952317e-01, -7.0306912e-02, ...,
          1.5542898e-01,  1.0329416e+00, -3.9985144e-01],
        [ 8.0126446e-01,  2.4110174e-01,  4.4332594e-02, ...,
          5.9928458e-02,  5.

In [ ]:
len(bert_results['encoder_outputs'])

12

In [ ]:
bert_results['encoder_outputs'][0]

<tf.Tensor: shape=(3, 128, 768), dtype=float32, numpy=
array([[[ 9.09636840e-02, -4.48403619e-02, -1.45858437e-01, ...,
         -2.95391679e-01, -1.90753460e-01,  9.62117910e-02],
        [ 4.12288308e-03, -3.51843610e-02,  1.21631479e+00, ...,
          1.56233990e+00, -2.80015796e-01,  1.29566801e+00],
        [-3.11931759e-01,  3.51246774e-01,  6.64722472e-02, ...,
          1.24530661e+00, -1.97829902e-01, -2.41880387e-01],
        ...,
        [ 2.56329358e-01,  2.23331377e-01,  3.16924274e-01, ...,
         -2.12727010e-01,  8.73437524e-03, -2.66483501e-02],
        [ 3.59660923e-01,  3.65453929e-01,  2.27703020e-01, ...,
         -1.87291950e-01,  8.56047571e-02,  1.05025016e-01],
        [ 3.72671634e-01,  4.17045236e-01,  2.65502036e-01, ...,
         -4.12917361e-02,  1.56412989e-01,  9.48973671e-02]],

       [[ 5.47647327e-02, -7.17151389e-02, -1.16446383e-01, ...,
         -2.96459436e-01, -1.63087264e-01,  9.71923023e-02],
        [ 2.30899081e-02, -2.00670157e-02,  1.25

In [ ]:
# the last encoder is same as sequence output
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']

<tf.Tensor: shape=(3, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  